# Random Quotes Generator
quotes = [
    {"quote": "The future depends on what you do today.", "author": "Mahatma Gandhi"},
    {"quote": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt"},
    {"quote": "Success is not final. Failure is not fatal.", "author": "Winston Churchill"},
    {"quote": "Dream big and dare to fail.", "author": "Norman Vaughan"},
    {"quote": "Don't watch the clock; do what it does. Keep going.", "author": "Sam Levenson"},
    {"quote": "Learning never exhausts the mind.", "author": "Leonardo da Vinci"},
    {"quote": "The best way to predict the future is to create it.", "author": "Peter Drucker"},
    {"quote": "Action is the foundational key to success.", "author": "Pablo Picasso"},
    {"quote": "Stay hungry. Stay foolish.", "author": "Steve Jobs"},
    {"quote": "Small steps every day lead to big results.", "author": "Unknown"},
    {"quote": "Discipline beats motivation.", "author": "Unknown"},
    {"quote": "Every expert was once a beginner.", "author": "Helen Hayes"},
    {"quote": "Done is better than perfect.", "author": "Sheryl Sandberg"},
    {"quote": "Opportunities don't happen. You create them.", "author": "Chris Grosser"},
    {"quote": "Never stop learning.", "author": "Unknown"},
    {"quote": "Success is earned, not given.", "author": "Unknown"},
    {"quote": "Push yourself because no one else will.", "author": "Unknown"},
    {"quote": "Make today count.", "author": "Unknown"},
    {"quote": "Your only limit is your mind.", "author": "Unknown"},
    {"quote": "Be stronger than your excuses.", "author": "Unknown"},
    {"quote": "Dream it. Wish it. Do it.", "author": "Unknown"},
    {"quote": "Consistency creates success.", "author": "Unknown"},
    {"quote": "Hard work beats talent when talent doesn't work hard.", "author": "Tim Notke"},
    {"quote": "Don't limit your challenges. Challenge your limits.", "author": "Unknown"},
    {"quote": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe"},
    {"quote": "Great things never come from comfort zones.", "author": "Unknown"},
    {"quote": "Success begins with self-belief.", "author": "Unknown"},
    {"quote": "You miss 100% of the shots you don't take.", "author": "Wayne Gretzky"},
    {"quote": "Keep moving forward.", "author": "Walt Disney"},
    {"quote": "Work hard in silence. Let success make the noise.", "author": "Frank Ocean"},
    {"quote": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh"},
    {"quote": "Success doesn't come from what you do occasionally. It comes from what you do consistently.", "author": "Marie Forleo"},
    {"quote": "A goal without a plan is just a wish.", "author": "Antoine de Saint-Exupéry"},
    {"quote": "The harder you work, the luckier you get.", "author": "Gary Player"},
    {"quote": "Don't be afraid to give up the good to go for the great.", "author": "John D. Rockefeller"},
    {"quote": "The secret of success is to do the common thing uncommonly well.", "author": "John D. Rockefeller Jr."},
    {"quote": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill"},
    {"quote": "If you can dream it, you can achieve it.", "author": "Zig Ziglar"},
    {"quote": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt"},
    {"quote": "You don't have to be great to start, but you have to start to be great.", "author": "Zig Ziglar"},
    {"quote": "Believe in yourself and all that you are.", "author": "Christian D. Larson"},
    {"quote": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
    {"quote": "Everything you can imagine is real.", "author": "Pablo Picasso"},
    {"quote": "The difference between ordinary and extraordinary is that little extra.", "author": "Jimmy Johnson"},
    {"quote": "Success is liking yourself, liking what you do, and liking how you do it.", "author": "Maya Angelou"},
    {"quote": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius"},
    {"quote": "The secret of getting ahead is getting started.", "author": "Mark Twain"},
    {"quote": "Mistakes are proof that you are trying.", "author": "Unknown"},
    {"quote": "Failure is simply the opportunity to begin again, this time more intelligently.", "author": "Henry Ford"},
    {"quote": "Great things are done by a series of small things brought together.", "author": "Vincent van Gogh"},
    {"quote": "The only person you should try to be better than is the person you were yesterday.", "author": "Unknown"},
    {"quote": "Success requires sacrifice, commitment, and determination.", "author": "Unknown"},
    {"quote": "Your future is created by what you do today, not tomorrow.", "author": "Robert Kiyosaki"},
    {"quote": "A winner is just a dreamer who never gave up.", "author": "Nelson Mandela"},
    {"quote": "The road to success and the road to failure are almost exactly the same.", "author": "Colin R. Davis"},
    {"quote": "Do what you love and love what you do.", "author": "Wayne Dyer"},
    {"quote": "The best investment you can make is in yourself.", "author": "Warren Buffett"},
    {"quote": "Knowledge is power.", "author": "Francis Bacon"},
    {"quote": "The mind is everything. What you think you become.", "author": "Buddha"},
    {"quote": "Success comes to those who focus on their goals.", "author": "Unknown"},
    {"quote": "Your attitude determines your direction.", "author": "Unknown"},
    {"quote": "Champions keep playing until they get it right.", "author": "Billie Jean King"},
    {"quote": "Great leaders create more leaders, not followers.", "author": "Unknown"},
    {"quote": "Leadership is action, not position.", "author": "Donald McGannon"},
    {"quote": "Innovation distinguishes between a leader and a follower.", "author": "Steve Jobs"},
    {"quote": "Creativity is intelligence having fun.", "author": "Albert Einstein"},
    {"quote": "The only impossible journey is the one you never begin.", "author": "Tony Robbins"},
    {"quote": "Success is the sum of small efforts repeated day after day.", "author": "Robert Collier"},
    {"quote": "The best preparation for tomorrow is doing your best today.", "author": "H. Jackson Brown Jr."},
    {"quote": "Don't wait for opportunity. Create it.", "author": "Unknown"},
    {"quote": "Focus on progress, not perfection.", "author": "Unknown"},
    {"quote": "Your growth is a reflection of your effort.", "author": "Unknown"},
    {"quote": "Every day is a new chance to improve yourself.", "author": "Unknown"},
    {"quote": "The pain you feel today will be the strength you feel tomorrow.", "author": "Unknown"},
    {"quote": "Success is built one step at a time.", "author": "Unknown"},
    {"quote": "Be patient with yourself. Great things take time.", "author": "Unknown"},
    {"quote": "Don't stop when you're tired. Stop when you're done.", "author": "Unknown"},
    {"quote": "Your dreams are valid. Work for them.", "author": "Unknown"},
    {"quote": "The best time to start was yesterday. The next best time is now.", "author": "Unknown"},
    {"quote": "Never let fear decide your future.", "author": "Unknown"},
    {"quote": "You are capable of more than you know.", "author": "Unknown"},
    {"quote": "A positive mindset creates positive results.", "author": "Unknown"},
    {"quote": "Success starts with believing that you can.", "author": "Unknown"},
    {"quote": "Great achievements require great preparation.", "author": "Unknown"},
    {"quote": "The future is built by those who prepare today.", "author": "Unknown"},
    {"quote": "Learn something new every day.", "author": "Unknown"},
    {"quote": "The expert in anything was once a beginner.", "author": "Helen Hayes"},
    {"quote": "Your effort today creates your success tomorrow.", "author": "Unknown"},
    {"quote": "Confidence comes from preparation and action.", "author": "Unknown"},
    {"quote": "Small progress is still progress.", "author": "Unknown"},
    {"quote": "Success is a journey, not a destination.", "author": "Arthur Ashe"},
    {"quote": "Never give up on something you truly believe in.", "author": "Unknown"},
    {"quote": "The difference between winning and losing is persistence.", "author": "Unknown"},
    {"quote": "Hard work creates opportunities.", "author": "Unknown"},
    {"quote": "Your mindset is your greatest tool.", "author": "Unknown"},
    {"quote": "The future belongs to the learners.", "author": "Unknown"},
    {"quote": "Growth begins outside your comfort zone.", "author": "Unknown"},
    {"quote": "Dreams become reality through action.", "author": "Unknown"},
    {"quote": "Success comes from commitment and consistency.", "author": "Unknown"},
    {"quote": "Keep learning, keep growing, keep improving.", "author": "Unknown"},
    {"quote": "The strongest people are built through challenges.", "author": "Unknown"},
    {"quote": "Believe in the process.", "author": "Unknown"},
    {"quote": "Make yourself proud.", "author": "Unknown"}
]
